// 10-angular/src/app/counter/counter.component.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';

@Component({
  selector: 'app-counter',
  template: `
    <div>
      <h2>Display of Counter</h2>
      <h1>{{ count }}</h1>
      <h1>{{ name }}</h1>
      <button (click)="increment()">Increment</button>
    </div>
  `,
  styles: [],
})
export class CounterComponent {
  state = { count: 0, name: 'Jonas' };

  get name() {
    console.log('get name');
    return this.state.name;
  }

  get count() {
    console.log('get count');
    return this.state.count;
  }

  increment() {
    this.state.count++;
  }
}

// 20-react/src/Counter.tsx
import React, { useState } from "react";

function CounterImpl() {
  let [state, setState] = useState({ number: 0, name: "Jonas" });

  function increment() {
    const newState = { ...state, number: state.number + 1 };
    setState(newState);
    console.log("state", state);
  }

  console.log("Render Counter");
  return (
    <div>
      <h2>Display of Counter.</h2>
      <h1>{state.number}</h1>
      <button onClick={increment}>Increment</button>
    </div>
  );
}

export const Counter = React.memo(CounterImpl);
